### ISSUE TITLE
Error during execution

### ISSUE THREAD

**Issue by jmaquet** [Smile-SA/node-pushserver#26]
I had the following error while the server was running :

+1: Feedback service, number of devices to remove: 0
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)

Notices that i didn't run any remove user action, i tried to send a notification to an ios device.

**Comment by jmaquet** [comment]
This bug was linked to an issue on port that were blocked by firewall.
i close this.
