### ISSUE TITLE
TypeError: Cannot read property 'connection' of undefined when sending APN

### ISSUE THREAD

**Issue by xyng** [Smile-SA/node-pushserver#36]
The Server crashes...

Error Message:
```
Listening on port 7777...
/usr/local/lib/node_modules/node-pushserver/node_modules/mongoose/lib/utils.js:419
        throw err;
              ^
TypeError: Cannot read property 'connection' of undefined
    at /usr/local/lib/node_modules/node-pushserver/lib/APNPusher.js:31:61
    at /usr/local/lib/node_modules/node-pushserver/node_modules/lodash/dist/lodash.js:4668:23
    at Object.push (/usr/local/lib/node_modules/node-pushserver/lib/APNPusher.js:16:5)
    at Object.send (/usr/local/lib/node_modules/node-pushserver/lib/PushController.js:25:19)
    at callback (/usr/local/lib/node_modules/node-pushserver/lib/Web.js:125:22)
    at Promise.<anonymous> (/usr/local/lib/node_modules/node-pushserver/lib/PushAssociations.js:96:16)
    at Promise.<anonymous> (/usr/local/lib/node_modules/node-pushserver/node_modules/mongoose/node_modules/mpromise/lib/promise.js:162:8)
    at Promise.emit (events.js:107:17)
    at Promise.emit (/usr/local/lib/node_modules/node-pushserver/node_modules/mongoose/node_modules/mpromise/lib/promise.js:79:38)
    at Promise.fulfill (/usr/local/lib/node_modules/node-pushserver/node_modules/mongoose/node_modules/mpromise/lib/promise.js:92:20)
```

Configuration:
```
{
    "webPort": 7777,

    "sqlitePath": "./database.sqlite",
     "mongodbUrl": "mongodb://localhost/push3",

    "gcm": {
        "apiKey": "********************************************************",
        "apiKey2": "********************************************************"
    },

    "apnDisabled": {
        "connection": {
            "gateway": "gateway.sandbox.push.apple.com",
            "cert": "apn/cert.pem",
            "key": "apn/key.pem",
            "ca": "apn/entrust_2048_ca.pem"
        },
        "feedback": {
            "address": "feedback.sandbox.push.apple.com",
            "cert": "apn/cert.pem",
            "key": "apn/key.pem",
            "ca": "apn/entrust_2048_ca.pem",
            "interval": 43200,
            "batchFeedback": true
        }
    }
}
```
I also tried to add the entrust ca (as you see in the config), which didn't change anything.
Also disabled my firewall - still crashing when sending it.
The openssl-tests from the APN-Setup documentation work fine (when specifying the CA).
GCM also worked fine before adding APN.

**Comment by marob** [comment]
Hi,

you use the "apnDisabled" key instead of "apn" in your configuration file
That would explain your problem.

Regards.

**Comment by xyng** [comment]
Oh. That happens when you look at the same config too long.. ;-)
Thank you!
