### ISSUE TITLE
Prevent from entering PEM pass phrase

### ISSUE THREAD

**Issue by alexbleks** [Smile-SA/node-pushserver#59]
Everytime I start the script and starts sending a push i Must enter the PEM pass phrase, is it possible to do this automatically?

**Comment by marob** [comment]
You should remove the pass phrase.

**Comment by alexbleks** [comment]
I cant, it results in a crash when a push hit.



/usr/local/lib/node_modules/node-pushserver/node_modules/apn/node_modules/q/q.js:155
                throw e;
                      ^
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Object.exports.createCredentials (crypto.js:100:17)
    at Object.exports.connect (tls.js:1334:27)
    at apnSocketLegacy (/usr/local/lib/node_modules/node-pushserver/node_modules/apn/lib/socket.js:36:19)
    at Feedback.loadCredentials.then.done.deferredConnection (/usr/local/lib/node_modules/node-pushserver/node_modules/apn/lib/feedback.js:163:17)
    at _fulfilled (/usr/local/lib/node_modules/node-pushserver/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/node-pushserver/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/node-pushserver/node_modules/apn/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/node-pushserver/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/node-pushserver/node_modules/apn/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/node-pushserver/node_modules/apn/node_modules/q/q.js:125:13)

**Comment by marob** [comment]
I think you broke your certificate. Can you test that your certificate is OK with `openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem` (assuming you're in sandbox mode)?

You should also take a look at this documentation for preparing the certificate: https://github.com/argon/node-apn/wiki/Preparing-Certificates

**Comment by alexbleks** [comment]
Great, where do I donate? :-)

**Comment by marob** [comment]
That's free :-)

**Comment by alexbleks** [comment]
Come on! Let me atleast buy you a beer!
